basePath: /endpoint
definitions:
  response.Message:
    properties:
      Code:
        type: integer
      Message:
        type: string
    type: object
host: localhost:3500
info:
  contact:
    email: freshmanlimited@gmail.com
    name: Amir Irani
  description: A user system API starter.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: GoWithWith
  version: "1.0"
paths:
  /user/auth/logout:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Session ID
        in: body
        name: id
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      security:
      - ApiKeyAuth: []
      summary: Delete session
      tags:
      - session
  /user/v1/auth/password:
    put:
      consumes:
      - application/json
      parameters:
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      summary: Change password
      tags:
      - user
  /user/v1/auth/sessions:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page
        in: query
        name: page
        type: number
      - description: Limit
        in: query
        name: limit
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get user sessions
      tags:
      - session
  /user/v1/signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: object
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      summary: User signin
      tags:
      - user
  /user/v1/signin/forgot:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      summary: Forgot password
      tags:
      - user
  /user/v1/signin/reset:
    post:
      consumes:
      - application/json
      parameters:
      - description: Token
        in: body
        name: token
        required: true
        schema:
          type: object
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      summary: Reset password
      tags:
      - user
  /user/v1/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: object
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: object
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      summary: Create an account
      tags:
      - user
  /user/v1/signup/resend:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      summary: Resend email verfication
      tags:
      - user
  /user/v1/signup/verification:
    post:
      consumes:
      - application/json
      parameters:
      - description: Token
        in: body
        name: token
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Message'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Message'
            type: object
      summary: Activate user account
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
